# -*- coding: utf-8 -*-
"""Assignment1.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pms72m4wQnvKPUyJ-T0KhS0MlnuTPM93

# StarWars GIF generator

There's ton of GIFs on Giphy, but how about a StarWars themed GIF? This module randomly picks a StarWars character in the franchise and provides you with a GIF

Following is the workflow:



1.   Run selection starwars character section
2.   Set up API
3.   Set up GIPHY
4.   Put it together!

# Selecting a random Starwars Character
In this section we will request to the public SWAPI https://swapi.dev/ to retrieve a random character
"""

#array of GIF-iable characters' ID
#check "Selecting only available characters to see how we came up with this array"
characters = [1, 2, 3, 4, 5, 10, 11, 13, 14, 20, 21, 22, 25, 35, 36, 32, 30, 44, 51, 69, 67, 79]

import random

def rando_number():
  random_index = random.randint(0, len(characters) - 1)
  random_number = characters[random_index]

  return random_number

"""
### Selecting only available characters"""

#mannual checker for all the characters on API

import requests

def fetch_character_T(num):

  url = f'https://swapi.dev/api/people/{num}/'

  r = requests.get(url)
  data = r.json()

  name = data['name']
  return name

#printing the characters name on list
for i in range (1,89):
  try:
    chr = fetch_character_T(i)
    pri = f"{i}: {chr}"

    print(pri)
  except:
    print("no data found")

"""https://chatgpt.com/share/a47863a2-2bb4-443c-b30f-e0c8c53a5964

Chatgpt link for extracting only the wanted names and their ID

### Fetching Character

We make an API call, retrieve data as json, and query the dictionary with "name" to filter the name
"""

#random character fetcher
import requests

def fetch_character():

  rd_character = rando_number()
  url = f'https://swapi.dev/api/people/{rd_character}/'

  r = requests.get(url)
  data = r.json()

  name = data['name']
  return name

"""# Setting up GIPHY

Navigate to https://developers.giphy.com/docs/api/endpoint and register for developers account

go to KEY icon on the left side and put your secret key
"""

#use ur own GIPHY key here for collab

from google.colab import userdata
GIPHY_KEY = userdata.get('GIPHY-KEY')

if GIPHY_KEY:
  print('KEY is valid')
else:
  print('Please check KEY status')

#retrieve GIPHY data
import json

def fetch_GIPHY():

  #here we use our fetch_character() function
  name = fetch_character()
  print("your character's name is: "+name)

  url = f'https://api.giphy.com/v1/gifs/search?api_key={GIPHY_KEY}&q={name}&limit=20&offset=5&rating=g&lang=en'
  re = requests.get(url)

  data = re.json()
  return data

#print the GIF
from IPython.display import HTML

def print_GIF():

  data = fetch_GIPHY()
  try:
    #important --> we navigate from the "data" on the previous cell to locate the embed_url from the json file
    embed_url = data['data'][0]['embed_url']
    # Embed the GIF using an iframe
    display(HTML(f'<iframe src="{embed_url}" width="480" height="270" frameborder="0" class="giphy-embed" allowfullscreen></iframe>'))
  except:
    #in case we have an unexpected error, we handle it
    print("We are sorry - unexpected error occured. Please try again")

"""# Try it yourself!"""

print('Welcome to random Star Wars GIF generator!')
print_GIF()